/**
 * Slots Studio — Jobs Development Fixtures
 *
 * ARCHITECTURAL NOTICE:
 * These fixtures provide initial sample background jobs across workspace studios
 * for UI development, testing, and layout demonstration.
 */

import { type Job } from "@/lib/jobs/types";

export const DEV_JOB_FIXTURES: Job[] = [
  {
    id: "job_dev_01",
    workspaceId: "ws_dev_sample",
    projectId: "proj_sample_01",
    projectName: "Technical Training Jacket",
    slotCode: "SS-02481",
    createdBy: "usr_dev_01",
    studio: "PRODUCT",
    jobType: "PRODUCT_CONCEPT_GENERATION",
    provider: "SlotsStudio-DevConceptEngine",
    status: "REVIEW",
    progressLabel: "AWAITING HUMAN REVIEW",
    inputSummary: "4 Silhouette Candidates • Technical Outerwear • Bonded Seams",
    outputIds: ["asset_dev_01", "asset_dev_02"],
    startedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 1.8).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1.8).toISOString(),
  },
  {
    id: "job_dev_02",
    workspaceId: "ws_dev_sample",
    projectId: "proj_sample_02",
    projectName: "Velocity Running Shoe",
    slotCode: "SS-00101",
    createdBy: "usr_dev_01",
    studio: "PRODUCT",
    jobType: "PRODUCT_CONCEPT_GENERATION",
    provider: "SlotsStudio-DevConceptEngine",
    status: "RUNNING",
    progressLabel: "SYNTHESIZING CANDIDATES",
    inputSummary: "3 Outsole Silhouette Candidates • Carbon Plate Geometry",
    outputIds: ["asset_dev_03"],
    startedAt: new Date(Date.now() - 3600000 * 0.5).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 0.5).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 0.2).toISOString(),
  },
  {
    id: "job_dev_03",
    workspaceId: "ws_dev_sample",
    projectId: "proj_sample_01",
    projectName: "Technical Training Jacket",
    slotCode: "SS-02481",
    createdBy: "usr_dev_01",
    studio: "PRODUCT",
    jobType: "PRODUCT_CONCEPT_REFINEMENT",
    provider: "SlotsStudio-DevConceptEngine",
    status: "COMPLETED",
    progressLabel: "GENERATION COMPLETE",
    inputSummary: "Refinement of Candidate Alpha • Taped Zipper Ergonomics",
    outputIds: ["asset_dev_01"],
    startedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 5.8).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5.8).toISOString(),
  },
  {
    id: "job_dev_04",
    workspaceId: "ws_dev_sample",
    projectId: "proj_sample_02",
    projectName: "Velocity Running Shoe",
    slotCode: "SS-00101",
    createdBy: "usr_dev_01",
    studio: "VISUAL",
    jobType: "ASSET_PROCESSING",
    provider: "SlotsStudio-Rasterizer",
    status: "FAILED",
    progressLabel: "PIPELINE INTERRUPTED",
    inputSummary: "360 Turntable High-Res Vector Rasterization",
    errorCode: "ERR_ASSET_TIMEOUT",
    errorMessageSafe: "Processing timed out while synthesizing high-res frames. Your project parameters remain safe.",
    startedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 11.9).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 11.9).toISOString(),
  },
  {
    id: "job_dev_05",
    workspaceId: "ws_dev_sample",
    projectId: "proj_sample_01",
    projectName: "Technical Training Jacket",
    slotCode: "SS-02481",
    createdBy: "usr_dev_01",
    studio: "CONTENT",
    jobType: "OTHER",
    provider: "SlotsStudio-ContentPipeline",
    status: "QUEUED",
    progressLabel: "QUEUED IN WORKSPACE PIPELINE",
    inputSummary: "Technical Garment Feature Bullets & Spec Copy Synthesis",
    createdAt: new Date(Date.now() - 3600000 * 0.1).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 0.1).toISOString(),
  },
];
